// Plain-language reference for WCAG 2.1/2.2 success criteria, keyed by SC
// number. Covers every A/AA criterion (what this tool actually targets) plus
// the AAA criteria axe-core commonly flags (scanned as "bonus" findings).
// Used to render the on-page "WCAG criteria in this report, decoded" section
// and to label the Principle (POUR) filter — scoped to whatever SCs actually
// showed up in the current report, not a full spec dump.
window.WCAG_GLOSSARY = {
  "1.1.1": { name: "Non-text Content", level: "A", principle: 1, description: "Images, icons, and other non-text content need a text alternative (alt text) that serves the same purpose." },
  "1.2.1": { name: "Audio-only and Video-only (Prerecorded)", level: "A", principle: 1, description: "Prerecorded audio-only or video-only content needs a text alternative or transcript." },
  "1.2.2": { name: "Captions (Prerecorded)", level: "A", principle: 1, description: "Prerecorded video with audio needs captions." },
  "1.2.3": { name: "Audio Description or Media Alternative (Prerecorded)", level: "A", principle: 1, description: "Prerecorded video needs an audio description or a full text alternative describing the visual content." },
  "1.2.4": { name: "Captions (Live)", level: "AA", principle: 1, description: "Live video with audio needs live captions." },
  "1.2.5": { name: "Audio Description (Prerecorded)", level: "AA", principle: 1, description: "Prerecorded video needs audio description of important visual information not covered by the existing audio." },
  "1.3.1": { name: "Info and Relationships", level: "A", principle: 1, description: "Structure (headings, lists, form labels, tables) must be marked up so it's programmatically detectable, not just visually implied." },
  "1.3.2": { name: "Meaningful Sequence", level: "A", principle: 1, description: "Content must read in a meaningful order when linearized (e.g. by a screen reader), matching the visual reading order." },
  "1.3.3": { name: "Sensory Characteristics", level: "A", principle: 1, description: "Instructions shouldn't rely solely on shape, color, size, or position (\"click the round button\") — pair with text." },
  "1.3.4": { name: "Orientation", level: "AA", principle: 1, description: "Content shouldn't be locked to one screen orientation (portrait/landscape) unless essential." },
  "1.3.5": { name: "Identify Input Purpose", level: "AA", principle: 1, description: "Common input fields (name, email, address...) should be programmatically identified via autocomplete attributes." },
  "1.4.1": { name: "Use of Color", level: "A", principle: 1, description: "Color can't be the only way information is conveyed (e.g. errors shown only by turning a field red)." },
  "1.4.2": { name: "Audio Control", level: "A", principle: 1, description: "Audio that plays automatically for more than 3 seconds needs a way to pause, stop, or mute it." },
  "1.4.3": { name: "Contrast (Minimum)", level: "AA", principle: 1, description: "Text needs at least 4.5:1 contrast against its background (3:1 for large text)." },
  "1.4.4": { name: "Resize Text", level: "AA", principle: 1, description: "Text must be resizable up to 200% without losing content or functionality." },
  "1.4.5": { name: "Images of Text", level: "AA", principle: 1, description: "Use real text instead of images of text where possible, so it can be resized/restyled/read by assistive tech." },
  "1.4.10": { name: "Reflow", level: "AA", principle: 1, description: "Content must be usable without 2D scrolling at a 320px-wide viewport (roughly 400% zoom on a 1280px design)." },
  "1.4.11": { name: "Non-text Contrast", level: "AA", principle: 1, description: "UI components (buttons, form field borders, focus indicators) and meaningful graphics need at least 3:1 contrast against adjacent colors." },
  "1.4.12": { name: "Text Spacing", level: "AA", principle: 1, description: "Content must remain usable when a user overrides line-height, paragraph spacing, letter/word spacing to more generous values." },
  "1.4.13": { name: "Content on Hover or Focus", level: "AA", principle: 1, description: "Tooltips/popovers triggered by hover or focus must be dismissible, hoverable, and stay visible until no longer needed." },
  "2.1.1": { name: "Keyboard", level: "A", principle: 2, description: "All functionality must be operable with a keyboard alone, no mouse required." },
  "2.1.2": { name: "No Keyboard Trap", level: "A", principle: 2, description: "If keyboard focus can move into a component, it must be able to move back out using just the keyboard." },
  "2.1.4": { name: "Character Key Shortcuts", level: "A", principle: 2, description: "Single-character keyboard shortcuts must be able to be turned off, remapped, or only active on focus." },
  "2.2.1": { name: "Timing Adjustable", level: "A", principle: 2, description: "Time limits must be adjustable, extendable, or removable by the user." },
  "2.2.2": { name: "Pause, Stop, Hide", level: "A", principle: 2, description: "Moving, blinking, scrolling, or auto-updating content needs a way to pause, stop, or hide it." },
  "2.2.3": { name: "No Timing", level: "AAA", principle: 2, description: "Timing shouldn't be an essential part of the activity at all." },
  "2.2.4": { name: "Interruptions", level: "AAA", principle: 2, description: "Interruptions (notifications, updates) can be postponed or suppressed by the user." },
  "2.2.5": { name: "Re-authenticating", level: "AAA", principle: 2, description: "If a session expires, the user can re-authenticate and continue without losing data." },
  "2.3.1": { name: "Three Flashes or Below Threshold", level: "A", principle: 2, description: "Content shouldn't flash more than 3 times per second (seizure risk)." },
  "2.3.2": { name: "Three Flashes", level: "AAA", principle: 2, description: "Content shouldn't flash more than 3 times per second, with no exceptions." },
  "2.4.1": { name: "Bypass Blocks", level: "A", principle: 2, description: "Provide a way to skip repeated content (nav bars, headers) to jump straight to the main content." },
  "2.4.2": { name: "Page Titled", level: "A", principle: 2, description: "Pages need a descriptive <title> that identifies the page's topic or purpose." },
  "2.4.3": { name: "Focus Order", level: "A", principle: 2, description: "Keyboard focus order must follow a sequence that preserves meaning and operability." },
  "2.4.4": { name: "Link Purpose (In Context)", level: "A", principle: 2, description: "A link's purpose should be clear from its text alone or from its surrounding context." },
  "2.4.5": { name: "Multiple Ways", level: "AA", principle: 2, description: "Provide more than one way to find a page (e.g. search plus navigation), unless it's a step in a process." },
  "2.4.6": { name: "Headings and Labels", level: "AA", principle: 2, description: "Headings and labels must actually describe their topic or purpose, not be vague filler text." },
  "2.4.7": { name: "Focus Visible", level: "AA", principle: 2, description: "Whatever has keyboard focus must have a visible indicator (outline, highlight)." },
  "2.4.8": { name: "Location", level: "AAA", principle: 2, description: "Users can tell where they are within a set of pages (breadcrumbs, site map, current-page indication)." },
  "2.4.9": { name: "Link Purpose (Link Only)", level: "AAA", principle: 2, description: "A link's purpose is clear from its link text alone, with no need for surrounding context." },
  "2.4.10": { name: "Section Headings", level: "AAA", principle: 2, description: "Section headings are used to organize content." },
  "2.4.11": { name: "Focus Not Obscured (Minimum)", level: "AA", principle: 2, description: "The focused element must not be entirely hidden by other content (e.g. a sticky header covering it)." },
  "2.4.12": { name: "Focus Not Obscured (Enhanced)", level: "AAA", principle: 2, description: "The focused element must not be hidden by other content at all, not even partially." },
  "2.4.13": { name: "Focus Appearance", level: "AAA", principle: 2, description: "The focus indicator must meet a minimum size and contrast so it's clearly visible." },
  "2.5.1": { name: "Pointer Gestures", level: "A", principle: 2, description: "Multi-point or path-based gestures (pinch, swipe) need a single-pointer alternative." },
  "2.5.2": { name: "Pointer Cancellation", level: "A", principle: 2, description: "Actions triggered by a pointer should be cancellable (e.g. by moving away before releasing)." },
  "2.5.3": { name: "Label in Name", level: "A", principle: 2, description: "A component's visible label text must be included in its accessible name, so voice-control users can reference it." },
  "2.5.4": { name: "Motion Actuation", level: "A", principle: 2, description: "Functionality triggered by device motion (shaking, tilting) needs an alternative that doesn't require motion." },
  "2.5.5": { name: "Target Size (Enhanced)", level: "AAA", principle: 2, description: "Clickable targets should be at least 44×44 CSS pixels." },
  "2.5.6": { name: "Concurrent Input Mechanisms", level: "AAA", principle: 2, description: "Users shouldn't be restricted to only one input method (e.g. touch-only, blocking keyboard/mouse)." },
  "2.5.7": { name: "Dragging Movements", level: "AA", principle: 2, description: "Drag-and-drop functionality needs a single-pointer alternative that doesn't require dragging." },
  "2.5.8": { name: "Target Size (Minimum)", level: "AA", principle: 2, description: "Clickable targets should be at least 24×24 CSS pixels, with some exceptions." },
  "3.1.1": { name: "Language of Page", level: "A", principle: 3, description: "The page's primary language must be set via the lang attribute on <html>." },
  "3.1.2": { name: "Language of Parts", level: "AA", principle: 3, description: "Passages in a different language than the page's default need their own lang attribute." },
  "3.1.3": { name: "Unusual Words", level: "AAA", principle: 3, description: "A mechanism is available for identifying the definition of unusual words, jargon, or idioms." },
  "3.1.4": { name: "Abbreviations", level: "AAA", principle: 3, description: "A mechanism is available for identifying the expanded form of abbreviations." },
  "3.1.5": { name: "Reading Level", level: "AAA", principle: 3, description: "Content requiring advanced reading ability has a simpler alternative available." },
  "3.1.6": { name: "Pronunciation", level: "AAA", principle: 3, description: "A mechanism is available for identifying the pronunciation of words where meaning is ambiguous without it." },
  "3.2.1": { name: "On Focus", level: "A", principle: 3, description: "Moving keyboard focus to an element shouldn't trigger an unexpected change of context (e.g. auto-submitting a form)." },
  "3.2.2": { name: "On Input", level: "A", principle: 3, description: "Changing a form field's value shouldn't trigger an unexpected change of context, unless the user is warned first." },
  "3.2.3": { name: "Consistent Navigation", level: "AA", principle: 3, description: "Repeated navigation must appear in the same relative order across pages." },
  "3.2.4": { name: "Consistent Identification", level: "AA", principle: 3, description: "Components with the same function must be identified consistently across pages (same icon, same label)." },
  "3.2.5": { name: "Change on Request", level: "AAA", principle: 3, description: "Changes of context only happen when the user requests them, never automatically." },
  "3.2.6": { name: "Consistent Help", level: "A", principle: 3, description: "If help (contact info, chat, FAQ) is offered, it appears in the same relative place across pages." },
  "3.3.1": { name: "Error Identification", level: "A", principle: 3, description: "Form errors must be identified and described to the user in text, not just visually (e.g. a red border)." },
  "3.3.2": { name: "Labels or Instructions", level: "A", principle: 3, description: "Form fields need labels or instructions describing what input is expected." },
  "3.3.3": { name: "Error Suggestion", level: "AA", principle: 3, description: "When an input error is detected, suggest how to fix it, if known and it doesn't compromise security." },
  "3.3.4": { name: "Error Prevention (Legal, Financial, Data)", level: "AA", principle: 3, description: "For legal/financial/data-modifying submissions, provide a way to review, confirm, or reverse the action." },
  "3.3.5": { name: "Help", level: "AAA", principle: 3, description: "Context-sensitive help is available." },
  "3.3.6": { name: "Error Prevention (All)", level: "AAA", principle: 3, description: "For any submission, provide a way to review, confirm, or reverse it." },
  "3.3.7": { name: "Redundant Entry", level: "A", principle: 3, description: "Information already entered earlier in a process shouldn't need to be re-entered manually (auto-fill or offer to reuse it)." },
  "3.3.8": { name: "Accessible Authentication (Minimum)", level: "AA", principle: 3, description: "Authentication shouldn't rely on a cognitive test (remembering a password, solving a puzzle) unless an alternative exists." },
  "3.3.9": { name: "Accessible Authentication (Enhanced)", level: "AAA", principle: 3, description: "Same as 3.3.8, with no exception for object recognition or personal-content puzzles." },
  "4.1.1": { name: "Parsing", level: "A", principle: 4, description: "HTML must be well-formed (no duplicate IDs, properly nested/closed tags) so assistive tech can parse it reliably." },
  "4.1.2": { name: "Name, Role, Value", level: "A", principle: 4, description: "Custom UI components must expose their name, role, and state programmatically (usually via ARIA) so assistive tech can identify and operate them." },
  "4.1.3": { name: "Status Messages", level: "AA", principle: 4, description: "Status updates (e.g. \"Item added to cart\") must be announced to assistive tech automatically, typically via aria-live, without moving focus." },
};

window.WCAG_PRINCIPLE_LABEL = { 1: "Perceivable", 2: "Operable", 3: "Understandable", 4: "Robust" };
